### ISSUE TITLE
genie -s  never returns

### ISSUE THREAD

**Issue by m-j-r** [arkane-systems/genie#7] opened 2019-06-24 09:56 UTC
Workaround exists, so no biggie ( ```$ genie -c bash``` works perfectly)

But otherwise, I get only the following and need to kill the process to continue.

```shell
$ genie -v -s
genie: outside bottle 27.
genie: starting shell
```

PS - other than this, works perfectly with Arch Linux, if you want to update your README.md

**Comment by cerebrate** [comment] 2019-06-24 11:53
Hm. Interesting. Can't repro this yet, but I'll see what I can come up with.

(Although given that the other issues I have on the open list - #5 and #6 - are both Arch-specific and weird, I might not give it the seal of approval just yet. 😕 😖 .)

**Comment by m-j-r** [comment] 2019-06-24 20:04
Problem with Arch is that every. single. user. has a different setup, so if one person gets it working - I'd take that as a win 😃 

For this issue - is there any logging or anything I can get for you? I'm also happy to change/compile some changes in if you point me in the right direction.

**Comment by zacharyrs** [comment] 2019-09-03 05:01
Just wanting to follow up on this...
I've managed to get Genie running on arch too, but can't launch into a shell.

``` powershell
wsl DOTNET_ROOT=/opt/dotnet/ genie -v -s
genie: outside bottle 17.
genie: starting shell
```

**Comment by cerebrate** [comment] 2019-09-04 15:06
Okay. For background both '-c' and '-s' are one-liners once the bottle is up. '-c' ends up executing

/usr/bin/nsenter  -t _systemdPid_ --wd="_currentDirectory_" -m -p su _username_ -c "command"

whereas '-s' executes:

/usr/bin/nsenter -t _systemdPid_ -m -p /bin/login -f _username_

Which suggests to me that the problem can't be with the `nsenter(1)`; it's essentially the same command. The problem's got to be with the `login(1)`.

So let's give this a try, by way of debugging. After you've got a bottle set up with `wsl genie -i`, start a WSL session outside the bottle and as root with `wsl -u root`. Then look up the bottle-external systemd pid, and try executing

/usr/bin/nsenter -t _systemdPid_ -m -p /bin/login -f _username_

manually. Let's see if that works, or fails, or if it produces any useful error information along the line.

If it fails, then let's try getting an strace from it with

strace -o dashc.strace -f /usr/bin/nsenter -t _systemdPid_ -m -p /bin/login -f _username_

and see if that reveals anything.

**Comment by zacharyrs** [comment] 2019-09-05 04:05
So I ran the above, with the strace output [here](https://pastebin.com/rauaTScq).

I'm assuming it's something on line 156?

**Comment by cerebrate** [comment] 2019-09-05 06:03
Looks like, that and previous. I believe the issue starts back at 143 or so (corresponding to line 1148 here - https://github.com/karelzak/util-linux/blob/master/login-utils/login.c#L1148 ), where login is trying to load locale information and failing.

(As for 156-159, I think that is to be expected from line 1221 here - https://github.com/karelzak/util-linux/blob/master/login-utils/login.c#L1221 - which appears to attempt to close all file descriptors > 2 without bothering to check whether or not they are currently open, hence the 1022 EBADFs. The prlimit64 syscall is the implementation of `get_fd_tabsize()` .)

161-171 have made it through to the `init_tty()` function, here - https://github.com/karelzak/util-linux/blob/master/login-utils/login.c#L360 - and the calls through line 171 match up with the code at least through line 406 - https://github.com/karelzak/util-linux/blob/master/login-utils/login.c#L406 .

Then we get a SIGTTOU, and I get lost, because as far as I know that's what happens when a background process tries to write to its controlling tty, and login should be the foreground process at this point, right?

I think the most likely explanation for the hang is whatever's causing that SIGTTOU, which I'll keep trying to figure out, but it may be worth looking into the locale thing, as the one similar issue I've been able to find is this one: https://superuser.com/questions/1426407/arch-linux-login-command-hangs .

**Comment by cerebrate** [comment] 2019-09-05 06:09
Meanwhile, in other things that might be worth trying, since it looks like it's failing during setup and before it invokes PAM to do the actual logging in, it might be worth trying and stracing just running

/bin/login -f _username_

and even just

/bin/login

directly in a `wsl -u root` session. They won't be able to start a login session run that way (since ptys aren't mentioned in /etc/securettys, at least on Debian), but it might be useful to see if they still fail in that simpler environment, and if so, is it in the same place?

**Comment by zacharyrs** [comment] 2019-09-05 07:28
So I'm pretty clueless regarding the actual `strace`, but I did try the bottom bit.

Seems I have the same crash when simply running `/bin/login`, with or without the `-f` option. From a quick skim the error looks identical, except some of the addresses, but I assume that's just due to reloading it all.

So it seems the issue is simply running `/bin/login` in WSL2?

**Comment by cerebrate** [comment] 2019-09-05 07:40
On Arch, anyway. I’ve tried the same /bin/login on Debian and Alpine on WSL 2, and the error doesn’t happen on them. 

Although if you look at that superuser.com post I linked up above, they’re getting the same error with the same strace on Arch native, which suggests this could be something unrelated to WSL 2, and we need to poke the Arch maintainers about it.

**Comment by zacharyrs** [comment] 2019-09-05 07:41
Woops, looks like we ran down the same thought path in parallel!

> So out of curiousity, I decided to just try call sudo /bin/login -f user on another archlinux machine - it seems to crash too?

**Comment by zacharyrs** [comment] 2019-09-05 07:46
Out of curiousity, what's the version number for `/bin/login` for you?

**Comment by cerebrate** [comment] 2019-09-05 13:50
util-linux 2.33.1-0.1

**Comment by zacharyrs** [comment] 2019-09-06 01:26
> util-linux 2.33.1-0.1 / login 1:4.5-1.1

Well that helped me figure it out!

Debian's `login` isn't from `util-linux`, it's from `shadow`. Arch has `login` from `util-linux`. See [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=833256).

Not sure where to go from here... I suppose the issue exists in the `util-linux` implementation of `login`. I could manually build `shadow` and `util-linux` to swap which `login` I've got, but that feels like a blunt solution.

**Comment by cerebrate** [comment] 2019-09-06 01:42
Ah, that would explain it.

And, yes, I think it's an issue with that login. So I think at this point the answer is probably taking it to the util-linux maintainer over at https://github.com/karelzak/util-linux , although I'd like to dig up a different distro that uses the util-linux /bin/login first just to be absolutely certain it's not a distro-specific issue.

**Comment by zacharyrs** [comment] 2019-09-06 02:11
Well it looks like fedora runs via util-linux, so I'll take a look at that too!

**Comment by cerebrate** [comment] 2019-09-06 06:44
For a temporary fix in the meantime, I have a possible crude hack.

If you try building login from util-linux (i.e. _./autogen.sh_; _./configure --enable-login_; _make_) after commenting out lines 416-418 of login.c, i.e.

```
	signal(SIGHUP, SIG_IGN);	/* so vhangup() won't kill us */
	vhangup();
	signal(SIGHUP, SIG_DFL);
```

I believe the resulting _login_ will complete successfully. Although I haven't been able to test this on Arch myself.

Disclaimer: While I believe that removing the call to [vhangup(2)](https://linux.die.net/man/2/vhangup) shouldn't break anything in this specific case (it's there to prevent password sniffing by the previous user on that tty), it's not a complete patch. Useful to know to come up with such a patch, though.

**Comment by cerebrate** [comment] 2019-09-07 20:16
Closing this for now as 1.8+ includes a workaround, and the fix is going to need to be in util-linux.

**Closed by cerebrate** 2019-09-07 20:16 UTC
Labels: bug, help wanted
