### ISSUE TITLE
all network routes lost after starting genie

### ISSUE THREAD

**Issue by macguges** [arkane-systems/genie#263] opened 2022-04-14 05:28 UTC
**Windows version (build number):**
Version 21H2 (OS Build 22000.613)

**Linux distribution:**
Debian bullseye

**Kernel version:**
5.10.102.1-microsoft-standard-WSL2

**Genie version:**
genie 2.3

**Describe the bug**
After running genie, networking does not work. 

From my investigation, it appeared that the problem was that all routes were flushed after running genie.  Through running genie under pdb, I'd identified the call to subprocess.run(startupChain) with startupChain = ['daemonize', '/usr/bin/unshare', '-fp', '--propagation', 'shared', '--mount-proc', '--', 'systemd'] as the point when networking was lost.

Most recently, I'd discovered upon restarting WSL2 and Debian that the ip routes and ip inet element under eth0 remained after running "genie -l", but network commands would still fail.

**Confirm that you are running inside the bottle:**
ben@hyperion-wsl:~$ genie -b
inside

**To Reproduce**
0. wsl --shutdown
1. open a shell into Debian WSL2
2. execute "sudo genie -l"

**Expected behavior**
I'd enter the bottle keeping the ability to reach the network.

**Screenshots**

**Additional context**
As I began documenting this problem, I began running Debian and Ubuntu shells under Terminal, to check the point when networking had been lost.  I could run "ip route" twice, before and after executing "sudo genie -l" in the Debian shell:

ben@hyperion:~$ ip route
default via 172.25.144.1 dev eth0
172.25.144.0/20 dev eth0 proto kernel scope link src 172.25.153.210
ben@hyperion:~$ ip route
ben@hyperion:~$

After running "genie -l", there would always be a long wait after "Waiting for systemd", but since I'd unregistered and reinstalled Debian I've not encountered errors from systemd.  But while preparing this bug report today I noticed that new routes would appear after the last "!":

ben@hyperion:~$ ip route
default via 172.25.144.1 dev eth0
172.25.144.0/20 dev eth0 proto kernel scope link src 172.25.153.210
ben@hyperion:~$ ip route
ben@hyperion:~$ ip route
default dev eth0 scope link
169.254.0.0/16 dev eth0 proto kernel scope link src 169.254.72.191

Following the author's recommendation, I have implemented bridged networking for WSL2.

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [ X ] Yes.

**Comment by ben-taylor-iboss** [comment] 2022-05-09 04:19
I'd be grateful to receive any feedback.  I'd run genie under pdb to hopefully provide some useful information for troubleshooting.   My next step would be to reinstall Debian and genie from scratch, taking care to be more thorough documenting my process, but if you have any suggestions for tests I could perform let me know.

**Comment by cerebrate** [comment] 2022-05-09 04:51
Genie itself does essentially nothing that touches on the network stack, as you can see from the source, (Updating the hostname and the hosts file aside.)

What is most probable (and consistent with your results that problems occur at the moment that systemd is started) is that there is an issue with whatever service _systemd_ is starting which serves the purpose of configuring your network settings. Under Debian bullseye, that is most probably _systemd-networkd_ , and since WSL without genie/systemd simply inherits its network settings and doesn't configure them, unless you've configured it appropriately yourself, it's doing the Wrong Thing.

There are some known issues documented on the wiki here caused by _systemd-networkd_ in a standard WSL configuration ( https://github.com/arkane-systems/genie/wiki/Systemd-units-known-to-be-problematic-under-WSL#systemd-networkdservice ); the solution there won't apply as is if you're using bridged networking, but your next step should be checking on _systemd-networkd_'s status with _systemctl status systemd-networkd_ and _networkctl_ to make sure that your network configuration is correct and it is behaving.

(Assuming your system is using _systemd-networkd_ ; if not, you'll need to check whatever it's actually using. But Debian bullseye uses _systemd-networkd_ by default, if I recall correctly.)

**Comment by macguges** [comment] 2022-05-09 05:05
Thank you.  I imagine you are likely correct, especially as the concept of virtual switches under Windows is new to me.  I will do as you've recommended, and if it's still unclear afterwards I could undo the bridged networking to reapproach using the default NAT-ed arrangement.

**Comment by cerebrate** [comment] 2022-05-30 16:17
Closing this for now; please re-open if you have continued problems.

**Closed by cerebrate** 2022-05-30 16:17 UTC
Labels: bug
