### ISSUE TITLE
make install ERROR

### ISSUE THREAD

**Issue by Yongqi-Liang** [arkane-systems/genie#312] opened 2023-10-07 09:03 UTC
**Linux distribution:**
WSL Oracle Linux 9.1

```shell
[liangyongqi@liangyongqi genie]$ ls
binsrc                       CONTRIBUTING.md  Makefile        README.md
CHANGELOG                    debian           othersrc
container-package-arch.sh    genie.spec       PKGBUILD
container-package-fedora.sh  LICENSE          readme-1.44.md
[liangyongqi@liangyongqi genie]$ make
# Build options include:
#
# Build binaries only.
#
# make build-binaries
#
# Package
#
# make package
# make package-debian
#   make package-debian-amd64
#   make package-debian-arm64
# make package-tar
# make package-arch (requires Arch packaging environment)
# make package-fedora (requires Fedora packaging environment)
#
# Clean up
#
# make clean
# make clean-debian
# make clean-tar
# make clean-arch
# make clean-fedora (requires Fedora packaging environment)
[liangyongqi@liangyongqi genie]$ make install
make: *** No rule to make target 'install'.  Stop.
``` 

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [x] Yes.

**Comment by cerebrate** [comment] 2023-11-10 16:54
There isn't a _make install_ option by design (it depends on too many system paths to conveniently support _/usr/local_ installation). If none of the packaging options work for you, you can run a _make package-tar_ to produce a tar archive of _genie_, but since if none of the packaging options work for you you're probably running some Linux varietal that I don't have/support, it leaves it up to you to put the binaries in the appropriate places for that distro. Sorry.

Closing this WONTFIX since _genie_ is now deprecated in favor of _bottle-imp_.

**Closed as completed by cerebrate** 2023-11-10 16:54 UTC
Labels: bug, wontfix
