### ISSUE TITLE
Anyone has already tried on CentOS 7 ?

### ISSUE THREAD

**Issue by vricosti** [arkane-systems/genie#311] opened 2022-11-18 09:08 UTC
Just want to know if it's available for RedHat/CentOS ?
To be more precise I would need to install it on CentOS7 and it seems that the requirements when I use Centora package are not met (glib is older , ...).
So I would need to repackage with the following deps:

- python 3.6.8 (I could update it to 3.7 but I dont think there are too much changes between those 2 versions)
- systemd-219 (instead of 232.25)
- GLIBC_2.17 (instead of GLIBC_2.34)

Is it possible ?

**Comment by cerebrate** [comment] 2022-11-18 19:24
CentOS 7, unfortunately, is probably out of luck. We ran into this issue way back in the day (January '21, or so) with genie 1.29, and the problem is that moving to `machinectl` (and away from a fairly gross `runuser` chain hack with a ppid bug) meant taking a hard dependency on systemd 232. The other deps may be fungible, but that one's going to be a sticking point.

At the time, the workaround amounted to grabbing the [1.28 release](https://github.com/arkane-systems/genie/releases/tag/1.28) (or code from the tag) and using that. That may still be a viable option, or at least one that could be made viable with a bit of hackage.

**Comment by vricosti** [comment] 2022-11-18 21:02
I have found a back port of systemd 231, it should be feasible to have a systemd 232…

**Closed as completed** 2022-11-28 09:55 UTC
Labels: enhancement

**Comment by vricosti** [comment] 2022-11-28 10:04
Issue not relevant
