### ISSUE TITLE
error starting lastest genie 1.33 - Debian buster - SOLVED!

### ISSUE THREAD

**Issue by rabsym** [arkane-systems/genie#102] opened 2021-01-26 12:24 UTC
Hello,

--- SOLVED ---
genie package should depend on gawk
--- SOLVED ---

After installing lastest genie I got the following error when init: (previously working at 1.30 version)

PS C:\WINDOWS\system32> wsl -d Debian -u root genie -s

```
Waiting for systemd....!
/bin/sh: 1: id: not found
/bin/sh: 4: [: Illegal number:

```

systemctl status shows running state not degraded

Any tip would be appreciated.
Thanks in advance.

**Comment by cerebrate** [comment] 2021-01-26 14:49
Nice catch!

Yeah, that's a regression. Looks like that dependency went missing when one but not all of the scripts using it were replaced. Fixed in 1.34.

**Closed by cerebrate** 2021-01-26 14:49 UTC
