### ISSUE TITLE
Not sure what I'm doing wrong

### ISSUE THREAD

**Issue by PeterKW** [arkane-systems/genie#199] opened 2021-09-05 07:40 UTC
**Windows version (build number):**
Find this by running `winver`

**Linux distribution:**
Manjaro

**Genie version:**
The output of `genie --version`

**Describe the bug**
peterwest@Lenovo:~/AppImages$ sudo wget https://github.com/arkane-systems/genie/releases/download/v1.44/genie-systemd-1.44-1-x86_64.pkg.tar.zst^C
peterwest@Lenovo:~/AppImages$ sudo pacman -U genie-systemd-1.44-1-x86_64.pkg.tar.zst
loading packages...
resolving dependencies...
warning: cannot resolve "daemonize", a dependency of "genie-systemd"
:: The following package cannot be upgraded due to unresolvable dependencies:
      genie-systemd

:: Do you want to skip the above package for this upgrade? [y/N] n
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'daemonize' required by genie-systemd

I'm not sure what I am doing wrong in the install process? 

I was trying to get journalctl working with systemd to store error reports

journalctl --system
No journal files were found.
-- No entries --

**Comment by nickcaballero** [comment] 2021-09-14 22:51
Duplicate of https://github.com/yuk7/ArchWSL/issues/197

**Comment by cerebrate** [comment] 2021-11-11 23:15
As @nickcaballero says. Fix should be as given there.

**Closed by cerebrate** 2021-11-11 23:15 UTC
Labels: bug
